# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zc_demo', '0002_auto_20160414_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ZingChartConfig',
        ),
    ]
