# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zc_demo', '0003_delete_zingchartconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZingChartConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('xAxis', models.CharField(max_length=20)),
                ('yAxis', models.CharField(max_length=20)),
                ('theme', models.CharField(max_length=20)),
                ('dangerRangeLow', models.IntegerField()),
                ('dangerRangeHigh', models.IntegerField()),
                ('warningRangeLow', models.IntegerField()),
                ('warningRangeHigh', models.IntegerField()),
                ('idleRangeLow', models.IntegerField()),
                ('idleRangeHigh', models.IntegerField()),
            ],
            options={
                'db_table': 'zingchart_config',
            },
        ),
    ]
